### ISSUE TITLE
tr warning and number of links lower than numer of videos in the playlist

### ISSUE THREAD

**Issue by megatux** [pierlauro/playlist2links#6]
This [playlist](https://www.youtube.com/playlist?list=PLGoFrwmx73Tp72OF4AgqxWSd_gWO_0EJk) says that have 295 videos, but the generated file has 293 lines:

```bash
$ ./playlist2links PLGoFrwmx73Tp72OF4AgqxWSd_gWO_0EJk
tr: atención: una barra invertida sin escape al final de la cadena no es transportable
tr: atención: una barra invertida sin escape al final de la cadena no es transportable

$ wc -l playlist_PLGoFrwmx73Tp72OF4AgqxWSd_gWO_0EJk.txt 
293 playlist_PLGoFrwmx73Tp72OF4AgqxWSd_gWO_0EJk.txt
```
sorry the Spanish, translated to something like _"Warning: a backslash with no escape at the end of the chain is not portable"_

**Comment by pierlauro** [comment]
If a playlist contains duplicate links, they will be saved only once: the playlist you linked contains two duplicate entries (indexes [153-154](https://www.youtube.com/watch?v=KByO6VvYNeg) and [155-156](https://www.youtube.com/watch?v=2YrwjXkL564) ).

I fixed the tr invocation, the warning was caused by duplicate entries; anyway it was not affecting the output.

[SOLVED](https://github.com/pierlauro/playlist2links/commit/2748f3bbfde661e3d85c081c7ca61d46e692aceb)
